baseURL = "https://awilddevappears.github.io"
languageCode = "en-us"
title = "AWildDevAppears"
theme = "wilddev"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"

  [[menu.main]]
    name = "Projects"
    url = "/projects"

  [[menu.main]]
    name = "Styleguide"
    url = "/styleguide"
